### ISSUE TITLE
מה צריך לתקן?

### ISSUE THREAD

**Issue by Oterem** [jce-il-ex/angular2-exercise-2-Oterem#1]
היי קובי. במשימה הזו נדרשנו ליצור 4 כפתורי ניווט. רציתי לערער על הציון. לא הבנתי למה קיבלתי 60 @kob-e

**Comment by YaakovHatam** [comment]
@Oterem  כתוב לי שחסר קישור אבל עכשיו הסתכלתי שוב וראיתי שישנו קישור, אתקן לך את הציון.
